// const baseURL = 'http://localhost:5000'
const baseURL = 'https://ask-pdf-sigma.vercel.app'
export const createUser = `${baseURL}/users`
export const loginUser = `${baseURL}/users/auth`
export const uploadSingleFile = `${baseURL}/upload/singlefile`
export const uploadMultiplefiles = `${baseURL}/upload/multiplefiles`
export const getFilesAPI = `${baseURL}/get/files`
export const chatAPI = `${baseURL}`
export const PaymentAPI = `${baseURL}/payment`
export const PaymentStatusAPI = `${baseURL}/payment/status`
